apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    name: portfolio-service
    app: portfolio-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: portfolio-pod
    app: portfolio-app