apiVersion: v1
kind: Pod
metadata:
  name: portfolio-pod
  labels:
    name: portfolio-pod
    app: portfolio-app
spec:
  containers:
    - name: karthi031000cit/portfolio:mkportfolio
      ports:
        - containerPort: 80
