# Generated by Django 5.1.2 on 2024-12-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk_portfolio', '0003_rename_certificates_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projects', models.CharField(max_length=200)),
            ],
        ),
    ]
