# Generated by Django 5.1.2 on 2024-12-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mk_portfolio', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
