# Generated by Django 5.1.2 on 2024-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk_portfolio', '0005_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projects', models.CharField(max_length=200)),
            ],
        ),
    ]
