# Generated by Django 5.1.2 on 2024-12-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mk_portfolio', '0006_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
