# Generated by Django 5.1.2 on 2024-12-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mk_portfolio', '0008_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
