# Generated by Django 5.1.2 on 2024-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk_portfolio', '0009_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
